##private
GET http://localhost:3000/api/v1/myFinance/user/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTc0NjA1NTAzOCwiZXhwIjoxNzQ2MTQxNDM4fQ.yXwm024_WSUxruMfro-F7Nb9eQEVuO2PfIC7t2zUmwQ
